import Head from 'next/head'

import { About, Blog, Features, Footer, Header, Possibility } from '../containers'
import { CTA, Brand, Navbar } from '../components'

export default function Home() {
  return (
    <>
      <Head>
        <title>Startup - 2</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div className='bg-gray-500'>
          <Navbar />
          <Header />
        </div>
        <main>
          <Brand />
          <About />
          <Features />
          <Possibility />
          <CTA />
          <Blog />
          <Footer />
        </main>
      </div>
    </>
  )
}
